### PR TITLE
V14 support

### PR DESCRIPTION
**Pull request by szolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/761)

### CODE REVIEW

**Review by tanbt — CHANGES_REQUESTED** [review]
@szolo  it works very well. I have a few tiny questions, plz check.

> Reviewed 18 of 20 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/761#-:-LgC9hol4Hinx7HJHOqY:b-ds3392)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @szolo and @tanbt)

___
*[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/platform/StarterManager.java, line 44 at r2](https://reviewable.io/reviews/vaadin/eclipse-plugin/761#-LgBl5NW7Wd0hTWLQ_Lw:-LgBl5NW7Wd0hTWLQ_Lx:bi0w4c1) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/8a075fa88ba71b682572c8ab96197d3f8d60a5f2/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/platform/StarterManager.java#L44)):*
> ```Java
> 
>     private static final String START_SERVICE_URL = "https://vaadin.com/vaadincom/start-service/";
>     private static final String STARTER_DOWNLOAD_URL = "https://vaadin.com/vaadincom/start-service/%s/%s";
> ```

It works when I tried `private static final String STARTER_DOWNLOAD_URL = START_SERVICE_URL + "%s/%s";`.
___
*[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/platform/StarterManager.java, line 70 at r2](https://reviewable.io/reviews/vaadin/eclipse-plugin/761#-LgC0iOhD-m-eg1ghiCk:-LgC0iOhD-m-eg1ghiCl:bqsdh1z) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/8a075fa88ba71b682572c8ab96197d3f8d60a5f2/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/platform/StarterManager.java#L70)):*
> ```Java
> 
>     public static Starter getSupportedStarter(Starter starter) {
>         if (!"pre-release".equals(starter.getRelease())
> ```

So we will only support`pre-release` starter projects, and when V14 is released, this status might be changed and we will fix it at that time.
Did I get it?

**Review by szolo — COMMENTED** [review]
@tanbt replied! 

> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/761#-:-LgCCshv2PlwgmZMeWaq:b-xbytu8)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @tanbt)

___
*[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/platform/StarterManager.java, line 44 at r2](https://reviewable.io/reviews/vaadin/eclipse-plugin/761#-LgBl5NW7Wd0hTWLQ_Lw:-LgCAyGa4qkUn0oBW7ug:b-tmdae) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/8a075fa88ba71b682572c8ab96197d3f8d60a5f2/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/platform/StarterManager.java#L44)):*
<details><summary><i>Previously, tanbt (Tan Bui) wrote…</i></summary><blockquote>

It works when I tried `private static final String STARTER_DOWNLOAD_URL = START_SERVICE_URL + "%s/%s";`.
</blockquote></details>

Good point, I think I missed that I already have the same constant. Thanks!
___
*[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/platform/StarterManager.java, line 70 at r2](https://reviewable.io/reviews/vaadin/eclipse-plugin/761#-LgC0iOhD-m-eg1ghiCk:-LgCBCXC8HLH_149qlF3:bb343wi) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/8a075fa88ba71b682572c8ab96197d3f8d60a5f2/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/platform/StarterManager.java#L70)):*
<details><summary><i>Previously, tanbt (Tan Bui) wrote…</i></summary><blockquote>

So we will only support`pre-release` starter projects, and when V14 is released, this status might be changed and we will fix it at that time.
Did I get it?
</blockquote></details>

Yeah, correct. Right now V14 is pre-release.

**Review by tanbt — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/761#-:-LgCFA5K81n_4SOFQv-_:b-uwkowd)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @tanbt)

**Review by tanbt — APPROVED** [review]
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/761)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
