### PR TITLE
Add analytic tracking

### PR DESCRIPTION
**Pull request by tanbt**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/796)

### CODE REVIEW

**Review by anssit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/796)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @tanbt)

___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/service/NotificationAnalytic.java, line 5 at r1](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-LrEMw6Y8dkWIMsJv3Cd:-LrEMw6ZCuRBreym34n8:bt8e69u) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c6f629f7bde05f18cd8d673e0ebc4ef7b4b2a587/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/service/NotificationAnalytic.java#L5)):*
> ```Java
> import com.google.gson.JsonObject;
> 
> public class NotificationAnalytic {
> ```

Merge this class with `ProjectAnalytic`. It can be called e.g. ` Tracker` or something similar.
___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/service/NotificationAnalytic.java, line 23 at r1](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-LrEN5ANDdrnsKw7zq7T:-LrEN5AO8b-225BIOo27:b-6ubrca) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c6f629f7bde05f18cd8d673e0ebc4ef7b4b2a587/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/service/NotificationAnalytic.java#L23)):*
> ```Java
>     public static boolean trackNotificationLinkClick(String link) {
>         JsonObject eventProps = null;
>         if (link != null) {
> ```

When merging with the other class, refactor this method to remove `JsonObject` related code duplication.

**Review by tanbt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/796)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @anssit)

___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/service/NotificationAnalytic.java, line 5 at r1](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-LrEMw6Y8dkWIMsJv3Cd:-LrEYtCg7Ne8FxC5V4UJ:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c6f629f7bde05f18cd8d673e0ebc4ef7b4b2a587/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/service/NotificationAnalytic.java#L5)):*
<details><summary><i>Previously, anssit wrote…</i></summary><blockquote>

Merge this class with `ProjectAnalytic`. It can be called e.g. ` Tracker` or something similar.
</blockquote></details>

Done.
___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/service/NotificationAnalytic.java, line 23 at r1](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-LrEN5ANDdrnsKw7zq7T:-LrEYtuR43rWXp6V17wR:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c6f629f7bde05f18cd8d673e0ebc4ef7b4b2a587/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/service/NotificationAnalytic.java#L23)):*
<details><summary><i>Previously, anssit wrote…</i></summary><blockquote>

When merging with the other class, refactor this method to remove `JsonObject` related code duplication. 
</blockquote></details>

Done.

**Review by anssit — DISMISSED** [review]
> Reviewed 4 of 12 files at r1, 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/796)* status: all files reviewed, 2 unresolved discussions (waiting on @tanbt)

___
*[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/notifications/model/Notification.java, line 124 at r2](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-LrID5R-DG9_v3h47jB8:-LrID5R-DG9_v3h47jB9:b-ocnval) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/23971cefb7b73f41d5dffaf84581b0c52811b965/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/notifications/model/Notification.java#L124)):*
> ```Java
> 
>         public Builder setLink(String link) {
>             notification.link = link + Tracker.UTM_TRACKING_PARAM;
> ```

Instead of publishing the `UTM_TRACKING_PARAM` constant, create a method in Tracker that adds it to the link. Like, `Tracker.getTrackableLink`.
___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java, line 43 at r2](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-LrIDPjR7l1ZSssPlU4D:-LrIDPjR7l1ZSssPlU4E:b-6ki2un) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/23971cefb7b73f41d5dffaf84581b0c52811b965/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java#L43)):*
> ```Java
>         if (!JavaPreferenceHandler
>                 .getBooleanValue(JavaPreferenceKey.INSTALLED)) {
>             if (Tracker.track(Tracker.INSTALL_EVENT_TYPE)) {
> ```

For consistency, don't publish the event constant, but add a method `Tracker.trackInstall()`.

**Review by tanbt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/796)* status: all files reviewed, 2 unresolved discussions (waiting on @anssit)

___
*[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/notifications/model/Notification.java, line 124 at r2](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-LrID5R-DG9_v3h47jB8:-LrIK4U-0dznEkWS1nSW:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/23971cefb7b73f41d5dffaf84581b0c52811b965/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/notifications/model/Notification.java#L124)):*
<details><summary><i>Previously, anssit wrote…</i></summary><blockquote>

Instead of publishing the `UTM_TRACKING_PARAM` constant, create a method in Tracker that adds it to the link. Like, `Tracker.getTrackableLink`.
</blockquote></details>

Done.
___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java, line 43 at r2](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-LrIDPjR7l1ZSssPlU4D:-LrILKnwB0eLHOTNMq_L:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/23971cefb7b73f41d5dffaf84581b0c52811b965/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java#L43)):*
<details><summary><i>Previously, anssit wrote…</i></summary><blockquote>

For consistency, don't publish the event constant, but add a method `Tracker.trackInstall()`.
</blockquote></details>

Done.

**Review by anssit — COMMENTED** [review]
Code looks good to me but not to the compiler? The build fails.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-:-LrIaIGh9QQzvaynu2Fu:ble0706)* status: all files reviewed, 1 unresolved discussion (waiting on @anssit)

**Review by anssit — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/796#-:-LrIgiCSAeUo-Pljb_iN:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @anssit)

**Review by anssit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/796)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
