### PR TITLE
Remove wysiwyg feature

### PR DESCRIPTION
**Pull request by makoivis**
Still incomplete in the sense that the old wysiwyg feature would need to have it's category changed, which requires configuring the build agents to work correctly. 

At least now you have to explicitly request installing the WYSIWYG editor.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/646)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[feature/feature.xml, line 66 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD4ItcALvvPLDyxlUi:-KBD4ItcALvvPLDyxlUj:-885614462) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/feature/feature.xml#L66)):_
perhaps this could be removed completely from the main feature

---

_[legacy-feature/feature.xml, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD41GzzFol3ZNQVYAT:-KBD41GzzFol3ZNQVYAU:658101955) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/feature.xml#L10)):_
update description to tell what this feature is for

---

_[legacy-feature/feature.xml, line 14 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD3rDeVQ7R4AfSUOvx:-KBD3rDeVQ7R4AfSUOvy:-1877138554) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/feature.xml#L14)):_
here, below and later also in other modules, we should update the copyright years

---

_[legacy-feature/feature.xml, line 33 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD48Hg9_SdDc-MM-DT:-KBD48Hg9_SdDc-MM-DU:-1653346378) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/feature.xml#L33)):_
(not quite sure if all of these are needed, but probably ok anyway)

---

_[legacy-feature/p2.inf, line 1 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD3NDoBsP8or7RR28x:-KBD3NDoBsP8or7RR28y:1106204531) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/p2.inf#L1)):_
(TBC that this works in various upgrade and install scenarios)

---

_[legacy-feature/pom.xml, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD38EKw3yKGBEAtlDz:-KBD38ELcssaainPNPTG:-1261523051) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/pom.xml#L10)):_
this comment is useful information but probably not quite accurate right now

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646)_

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[legacy-feature/feature.xml, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD41GzzFol3ZNQVYAT:-KBHFr-ERCA6xJNlD8jq:-1199670210) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/feature.xml#L10)):_
could add a mention that this is superceded by the new Vaadin Designer, and maybe also the word "old" in the beginning

---

_[legacy-feature/p2.inf, line 1 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD3NDoBsP8or7RR28x:-KBHFeLeJXYnnCM4_Xbm:-1162339829) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/p2.inf#L1)):_
(not here in reviewable, but being tested separately)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646)_

**Comment by makoivis** [comment]
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

_[feature/feature.xml, line 66 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD4ItcALvvPLDyxlUi:-KBDar3PYUrWJ4IKzara:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/feature/feature.xml#L66)):_
Done.

---

_[legacy-feature/feature.xml, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD41GzzFol3ZNQVYAT:-KBHLnNXWQrNgQqdHoUz:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/feature.xml#L10)):_
Done.

---

_[legacy-feature/feature.xml, line 14 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD3rDeVQ7R4AfSUOvx:-KBDb3UxgqkSbqpN0ozc:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/feature.xml#L14)):_
Done.

---

_[legacy-feature/p2.inf, line 1 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD3NDoBsP8or7RR28x:-KBDb6tmLBIrUKaUBgJS:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/p2.inf#L1)):_
Done.

---

_[legacy-feature/pom.xml, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646#-KBD38EKw3yKGBEAtlDz:-KBDb9BJZhXA8MuCOzxY:891948556) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/4670a26b668094432c85b7e68b1890c8abe004b3/legacy-feature/pom.xml#L10)):_
True. Will fix. 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646)_

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/646)_

**Pull request closed without merging**
