### PR TITLE
Add help for New Vaadin Maven Project wizard

### PR DESCRIPTION
**Pull request by hesara**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/648)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 133 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/648#-KBIMXcfn1pJVQMVYM9-:-KBIMXcgJHLvOOtW-0xG:1460996419) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/42f79e010ca825a30ccfe39bfc3e610dce788ac9/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L133)):_
White space issue

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/648)_

**Comment by tsuoanttila** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/648)_

**Comment by hesara** [comment]
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 133 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/648#-KBIMXcfn1pJVQMVYM9-:-KBINAlVSaCGiFV4zxAy:-497468049) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/42f79e010ca825a30ccfe39bfc3e610dce788ac9/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L133)):_
Fixed

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/648)_

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/648)_

**Pull request closed without merging**
