### PR TITLE
Download maven archetypes metadata from vaadin.com

### PR DESCRIPTION
**Pull request by elmot**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/655)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
There's typo in the pull request topic. Should be "metadata".

Could be shortened to "Download archetype metadata" and add the mention of download location to the description.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-:-KCF_IJcVHwiy5-Vlb7d:1403074705)_

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 26 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCF_ytOeqW_k3I55_7f:-KCF_ytOeqW_k3I55_7g:1863930324) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L26)):_
We should consider moving VaadinArchetype from a nested class to a proper public class if it's used in several locations.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 42 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCFemGCXZwkakeyzSZs:-KCFemGCXZwkakeyzSZt:287906362) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L42)):_
Might actually make sense to make this final Set<VaadinArchetype> and provide a sane .equals for that class. This way we could check .isEmpty() instead of a null check and do .addAll() instead of assignment. Just a thought, needs some planning though.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 54 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCFeDo03CmECicAY8CS:-KCFeDo03CmECicAY8CT:1935176478) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L54)):_
In my opinion this method should be restructured in to one if clause, where the returning of defaults is done in the catch part.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 74 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCFdvytlBD6A4ppoCZo:-KCFdvytlBD6A4ppoCZp:-1966358079) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L74)):_
Style nit: Add brackets for the if

Also: Do we really want to cache the default archetypes? Shouldn't we retry if it's a temporary problem ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655)_

**Comment by elmot** [comment]
_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 74 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCFdvytlBD6A4ppoCZo:-KCGcLGYQNsVmYN3LfYk:-1892783118) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L74)):_
I think we want. If the user is somewhere abroad without connectivity at all, he should see latest archetypes list but not default (possibly complete outdated) one.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655)_

**Comment by elmot** [comment]
_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 54 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCFeDo03CmECicAY8CS:-KCGVORU1Z-lFeeVjl_G:-212249514) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L54)):_
One one-line method will be inlined but  I'm going to keep  rest 2 methods separated just to keep the code self-explanatory.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655)_

**Comment by elmot** [comment]
_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 42 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCFemGCXZwkakeyzSZs:-KCGV70f1-iYoKvbdyYX:1637780693) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L42)):_
Well, all the code here should be refactored this way. Why only archetypes?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655)_

**Comment by tsuoanttila** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 42 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCFemGCXZwkakeyzSZs:-KCGoDllgj8Tfi2CtY7J:-639867569) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L42)):_
I guess it's fine for now at least.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 74 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCFdvytlBD6A4ppoCZo:-KCGoZ3t5i2u9WpM44Ah:1132444860) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/f697d7f816d874f1211998903985ccda88e7ade1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L74)):_
Ok for now at least

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655)_

**Comment by hesara** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/default-maven-archetypes.xml, line 1 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCKMqQp0LHbtUMo4bw_:-KCKMqQp0LHbtUMo4bwa:803548811) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/49a6e19626c24128396eb8afbe2246252434a9be/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/default-maven-archetypes.xml#L1)):_
this file probably shouldn't be under src at all, and should be listed in build.properties . Otherwise, even though it might work in the local development environment based on the classpath, it probably won't be included in released versions of the plug-in.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655)_

**Comment by hesara** [comment]
Reviewed 2 of 4 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 98 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655#-KCKzn7idyhM0ZALk9ro:-KCKzn7idyhM0ZALk9rp:233798156) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/e474c0a45ab945b9ad67b55f5c5c61bb66ca595b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L98)):_
To test that this also works with a version built on r2d2

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655)_

**Comment by tsuoanttila** [comment]
Reviewed 2 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/655)_

**Pull request closed without merging**
