### PR TITLE
Branding of the New Vaadin 7 Maven Project wizard

### PR DESCRIPTION
**Pull request by hesara**
- Set the background color and logo in the wizard banner.
- Update related texts.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/649)

### CODE REVIEW

**Comment by makoivis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionPage.java, line 24 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/649#-KBMkTZl9LwJQDfO-8jG:-KBMkTZl9LwJQDfO-8jH:678074825) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/483439f35100ebc61023098cd3e29bd8603a87f2/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionPage.java#L24)):_
typo

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/649)_

**Comment by tsuoanttila** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 73 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/649#-KBMl9FGnDk08GLJotqN:-KBMl9FGnDk08GLJotqO:480687197) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/483439f35100ebc61023098cd3e29bd8603a87f2/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L73)):_
We might want to consider moving this functionality or at least parts of it to the VaadinTitle (so making new vaadin branded wizards wouldd be easier)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/649)_

**Comment by hesara** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionPage.java, line 24 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/649#-KBMkTZl9LwJQDfO-8jG:-KBMmWyXkbaHps2CkB5U:-497468049) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/483439f35100ebc61023098cd3e29bd8603a87f2/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionPage.java#L24)):_
Fixed

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 73 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/649#-KBMl9FGnDk08GLJotqN:-KBMm_Fp6mie1VIIIB_Q:1247285867) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/483439f35100ebc61023098cd3e29bd8603a87f2/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L73)):_
To consider doing this later - somewhat more involved and sharing code with the designer

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/649)_

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/649)_

**Pull request closed without merging**
