### PR TITLE
Trigger widgetset compilation in m2e builds when needed

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/677)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
@hesara, please take a look

**Comment by hesara** [comment]
I'll take a look at the issues identified and the configurability of widgetset compilation

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java, line 111 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-KDPXsxxrdJVc2bYrbMU:-KDPXsxxrdJVc2bYrbMV:-709628321) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/974bef5324a6d9f39cfbe27d5db9b324cec3db2b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java#L111)):_
implement two settings:
- enable/disable preconfigure ws compile
- enable/disable other automatic ws compile

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java, line 175 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-KDPXqOel0QEO0qlsXmW:-KDPXqOel0QEO0qlsXmX:979863123) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/974bef5324a6d9f39cfbe27d5db9b324cec3db2b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java#L175)):_
add null check

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-:-KDPYG-igKsR9u9-r2j4:1935018202)_

**Comment by hesara** [comment]
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java, line 111 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-KDPXsxxrdJVc2bYrbMU:-KDPotEDCAh1sAh_iv1X:677588487) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/974bef5324a6d9f39cfbe27d5db9b324cec3db2b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java#L111)):_
done

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java, line 175 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-KDPXqOel0QEO0qlsXmW:-KDPowKNPMv5GH3-U4vW:676635175) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/974bef5324a6d9f39cfbe27d5db9b324cec3db2b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java#L175)):_
Done

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677)_

**Comment by tsuoanttila** [comment]
Reviewed 2 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java, line 74 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-KDQ-nRaBkaGoa4wVmIT:-KDQ-nRaBkaGoa4wVmIU:-785758170) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/51ddcf8b9250308cd27199e91bd549b7d8b60f2a/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java#L74)):_
What is this magic number 10? Also couple of other magic numbers in the same file

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/preferences/PreferenceInitializer.java, line 37 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-KDQ0QakJwcK4jfufq6W:-KDQ0Qal8eqzRYxLlXy0:-1887157378) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/51ddcf8b9250308cd27199e91bd549b7d8b60f2a/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/preferences/PreferenceInitializer.java#L37)):_
TODO needs to be addressed asap

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677)_

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java, line 74 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-KDQ-nRaBkaGoa4wVmIT:-KDS6Fz1niZc7Dnuwdgs:150720886) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/51ddcf8b9250308cd27199e91bd549b7d8b60f2a/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/maven/VaadinMojoExecutionBuildParticipant.java#L74)):_
It just should match the sum of the SubProgressMonitor ticks, and does not need to be accurate but just give a rough impression on how we expect the relative durations of the phases to be. If the number is too small in some cases if e.g. some branch is skipped, that is not a problem as monitor.done() will take it to its maximum.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/preferences/PreferenceInitializer.java, line 37 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-KDQ0QakJwcK4jfufq6W:-KDS6jtEploOOWwooR_B:-704002083) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/51ddcf8b9250308cd27199e91bd549b7d8b60f2a/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/preferences/PreferenceInitializer.java#L37)):_
can be in a separate patchset - I believe false is a safer default until tested more extensively

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677)_

**Comment by tsuoanttila** [comment]
@makoivis, want to take the final look at this?

**Comment by makoivis** [comment]
VaadinMojoExecutionBuildParticipant.java is starting to get a bit long, might require refactoring at a future date. other than that, LGTM.

---

Reviewed 2 of 3 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-:-KDSuCsNYxiiLg1492Zu:-568996578)_

**Comment by makoivis** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/677#-:-KDSuRYKabPkBFKyXo1a:1417088721)_

**Pull request closed without merging**
