### PR TITLE
New icons for plugin 2.4

### PR DESCRIPTION
**Pull request by elmot**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/35)

### CODE REVIEW

**Comment by makoivis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/35#-KAeCCcDzb5fDG7vzEGH:-KAeCCcDzb5fDG7vzEGI:792478583) (no related file):_
Looks good, but I would prefer to eliminate the whitespace changes. 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/35)_

**Comment by makoivis** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/35)_

**Comment by makoivis** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/35)_

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/35)_

**Pull request merged**
