### PR TITLE
New maven project wizard

### PR DESCRIPTION
**Pull request by tsuoanttila**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/5)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 7 files at r1, 2 of 3 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_[com.vaadin.integration.eclipse/plugin.xml, line 79 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdtMJeB8ANtEhh4083:-KAdtMJeB8ANtEhh4084:-1020437503) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/plugin.xml#L79)):_
"Vaadin7 Ivy Project (deprecated)" for consistency with the rest?

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionPage.java, line 27 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdtoW6GZGh7RE3nxVa:-KAdtoW6GZGh7RE3nxVb:-244265332) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionPage.java#L27)):_
in theory, both getContainer() and getNextPage() could return null here

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 22 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdub8gr0MgWJeJ9iRZ:-KAdub8gr0MgWJeJ9iR_:261030347) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L22)):_
useless javadoc + missing parameter

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 42 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdye2CL8_XVLP5zByQ:-KAdye2CL8_XVLP5zByR:-698471137) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L42)):_
(for a separate change that addresses the look and behavior of archetype selection)

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 60 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdytVqK-E4vyDA--ti:-KAdytVqK-E4vyDA--tj:2033078653) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L60)):_
this would probably be better done with a list component if possible - in a later change

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 93 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduuX5_zWsYV7mI5-s:-KAduuX5_zWsYV7mI5-t:433045161) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L93)):_
ideally, this class should not know the host page (maybe only a minimal listener if something is needed)

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 101 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdz43BAWsd35lJnnw4:-KAdz43BAWsd35lJnnw5:-1631537416) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L101)):_
later we probably want to replace the "click to proceed" with simple "click to select" behavior

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 230 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduJj-1Rt4m_ePG6VU:-KAduJj-1Rt4m_ePG6VV:-484269230) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L230)):_
can getVaadinArchetype() return null?

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 278 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduObqDrV6QEyPdgzw:-KAduObqDrV6QEyPdgzx:-484269230) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L278)):_
can getVaadinArchetype() return null?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5)_

**Comment by hesara** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 66 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdzuPhBczAccG850n5:-KAdzuPhBczAccG850n6:-1661204602) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L66)):_
something should be done about this - or perhaps just update the fallback to the currently latest version

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 78 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe-ODloYLQN3bu5TNn:-KAe-ODloYLQN3bu5TNo:1203765021) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L78)):_
titles, descriptions and list to be updated in a later change

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 137 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe02ryWjKrURt6Mj_U:-KAe02ryWjKrURt6Mj_V:-1709207303) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L137)):_
can this be called multiple times? if so, is there a better place to add the listener?

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 169 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe-wLf60-NZ6yplgkH:-KAe-wLf60-NZ6yplgkI:-1437471129) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L169)):_
remove the commented out code

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 238 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe10XAdjHpdD_CFTHR:-KAe10XAdjHpdD_CFTHS:-414198327) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L238)):_
(risk of the typo being corrected in later m2e versions)

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 276 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe1JCfOkWCBry5uHB9:-KAe1JCfOkWCBry5uHBA:1049936565) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L276)):_
perhaps this method could use javadoc

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5)_

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 93 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduuX5_zWsYV7mI5-s:-KAe6P5ZmxFdfDnp9li2:450139700) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L93)):_
A simple callback could be nice. A callback could also save us some trouble in the wizard itself as well.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 137 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe02ryWjKrURt6Mj_U:-KAe6EBFHCj4xKz9ykjt:-1992508694) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L137)):_
Not sure, needs investigation.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 230 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduJj-1Rt4m_ePG6VU:-KAe6AQlZmNLG3634wU2:1049815272) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L230)):_
At least now it shouldn't, not sure if eclipse can mess it up.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 276 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe1JCfOkWCBry5uHB9:-KAe5yV0N_QcPVw2ne3k:-633118859) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L276)):_
This method might need to be changed to somewhere else anyway, depending on how we do the wizard flow.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 278 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduObqDrV6QEyPdgzw:-KAe5rdGJzIJhHdbfqkl:1049815272) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L278)):_
At least now it shouldn't, not sure if eclipse can mess it up.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5)_

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/ArchetypeSelectionCallback.java, line 9 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAeDFYo6I6nM6sDNB6J:-KAeDFYo6I6nM6sDNB6K:-2112068012) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/03f81dbaa7ac73528a9c9c518c55d3a120d3d3d6/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/ArchetypeSelectionCallback.java#L9)):_
no need for empty @since

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 230 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduJj-1Rt4m_ePG6VU:-KAeDg6lQlQ1lsZ7nX4E:-1958196949) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L230)):_
It might be a good idea to guard against this anyway, e.g. if the user can later deselect the archetype

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 278 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduObqDrV6QEyPdgzw:-KAeDqKlE_rwCphruQwX:752833140) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L278)):_
Assuming that the parameter is never null - please acknowledge if so

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5)_

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_[com.vaadin.integration.eclipse/plugin.xml, line 79 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdtMJeB8ANtEhh4083:-KAeEa2lm6RjBkRocwhW:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/plugin.xml#L79)):_
Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/ArchetypeSelectionCallback.java, line 9 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAeDFYo6I6nM6sDNB6J:-KAeEtcsjgdndaSZLLfV:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/03f81dbaa7ac73528a9c9c518c55d3a120d3d3d6/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/ArchetypeSelectionCallback.java#L9)):_
Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionPage.java, line 27 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdtoW6GZGh7RE3nxVa:-KAeF9-b57MXvRIYJT96:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionPage.java#L27)):_
Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 22 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdub8gr0MgWJeJ9iRZ:-KAeFBUD5CRHVR9_TEVz:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L22)):_
Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 66 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAdzuPhBczAccG850n5:-KAeFKPJda2h6mRtnPsX:1011011911) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L66)):_
Indeed. This should be fixed, but I'd prefer to do it in a separate patch set.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 137 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe02ryWjKrURt6Mj_U:-KAeFTh_h7j5_ieOkDT7:-1779745968) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L137)):_
Method removed. No longer a problem

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 169 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAe-wLf60-NZ6yplgkH:-KAeFbVv0h8i2UU4v0ba:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L169)):_
Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 230 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduJj-1Rt4m_ePG6VU:-KAeFlWaoJRdRHwgmWEV:-836294618) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L230)):_
Part of performFinish method, that should not be called if a page returns false for isPageComplete (in this case return selectedArchetype != null && super...())

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 278 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5#-KAduObqDrV6QEyPdgzw:-KAeG7YUCVzx3uWBS6Cj:-64325281) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ccb43c835ed17137462ea011c6d97895bf44fc1c/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L278)):_
Now passed as a parameter. Should never be null. If indexing fails, will be IOOBException.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5)_

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/5)_

**Pull request merged**
