### PR TITLE
Add maven project creation wizard for Vaadin 8

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/721)

### CODE REVIEW

**Comment by ahie** [comment]
Code cleanup was only run on files that were edited in the previous patch.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-:-KVz92liwV7ykNiXfp5A:bdfdsno)_

**Comment by hesara** [comment]
Reviewed 6 of 11 files at r1.
Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 88 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzG0Lr_2_4dywzhIt9:-KVzG0Lr_2_4dywzhItA:b4mctmd) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/60f877f0fa20a2303e8e5d7b21a7af8d798b88fc/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L88)):_

> ``` Java
>             if (vaadinArchetype.getArchetype().getVersion()
>                     .matches(versionRegex)) {
>                 if (!vaadinArchetype.isPrerelease()) {
> ```

this whole if-else could be simply if (includePrereleases || !vaadinArchetype.isPrerelease()) ... which IMO is clear enough

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin8MavenProjectWizard.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzG_0C5Ky2GxXMTdGM:-KVzG_0C5Ky2GxXMTdGN:byhlnts) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/60f877f0fa20a2303e8e5d7b21a7af8d798b88fc/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin8MavenProjectWizard.java#L30)):_

> ``` Java
>                 .getBoolean(PreferenceConstants.PRERELEASE_ARCHETYPES_ENABLED);
>         List<VaadinArchetype> vaadinArchetypes = MavenVersionManager
>                 .getAvailableArchetypes(includePrereleases, "8.*");
> ```

for "theoretical correctness," could use "8\..*" or something like that

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectArchetypeSelectionPage.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzGvG5X4SqS_VGT2Fx:-KVzGvG5X4SqS_VGT2Fy:b-n33p3u) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/1dc852e0b77796cf97f45c2642fbc263392c81bb/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectArchetypeSelectionPage.java#L22)):_

> ``` Java
> 
>     public void createControl(Composite parent) {
>         // set by the wizard for all pages
> ```

Is this comment now incorrect/irrelevant or was only the version number incorrect?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721)_

**Comment by ahie** [comment]
Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 88 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzG0Lr_2_4dywzhIt9:-KW1kZPMikGjRO22NFC_:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/60f877f0fa20a2303e8e5d7b21a7af8d798b88fc/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L88)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> this whole if-else could be simply if (includePrereleases || !vaadinArchetype.isPrerelease()) ... which IMO is clear enough
> </details>
> Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin8MavenProjectWizard.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzG_0C5Ky2GxXMTdGM:-KW1kjPs3BHuCnmfcWyb:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/60f877f0fa20a2303e8e5d7b21a7af8d798b88fc/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin8MavenProjectWizard.java#L30)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> for "theoretical correctness," could use "8\..*" or something like that
> </details>
> Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectArchetypeSelectionPage.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzGvG5X4SqS_VGT2Fx:-KW1lEF9p3izR6ryjoAn:b-6qsrq2) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/1dc852e0b77796cf97f45c2642fbc263392c81bb/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectArchetypeSelectionPage.java#L22)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> Is this comment now incorrect/irrelevant or was only the version number incorrect?
> </details>
> I'd say it's now irrelevant since both wizards now clearly set their own page titles.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721)_

**Comment by hesara** [comment]
Reviewed 3 of 11 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin8MavenProjectWizard.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzG_0C5Ky2GxXMTdGM:-KW1tBI_64GvGouj8q1p:b-bp1rtb) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/60f877f0fa20a2303e8e5d7b21a7af8d798b88fc/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin8MavenProjectWizard.java#L30)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Done.
> </details>
> only done below, not in the condition above

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectArchetypeSelectionPage.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzGvG5X4SqS_VGT2Fx:-KW1tMsv4NRanMte_KE5:b-dxdgpe) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/1dc852e0b77796cf97f45c2642fbc263392c81bb/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectArchetypeSelectionPage.java#L22)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> I'd say it's now irrelevant since both wizards now clearly set their own page titles.
> </details>
> I guess the idea that the wizard sets the title is still valid, but not a problem

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectWizard.java, line 58 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KW1u_H4llmKvzI-fAa4:-KW1u_H4llmKvzI-fAa5:blrb05k) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/e01fd7bb11c38f948058c7ea18a5ac856fd15de1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectWizard.java#L58)):_

> ``` Java
> 
>     /**
>      * Default constructor. Sets the title and image of the wizard.
> ```

no longer sets the title?

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectWizard.java, line 83 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KW1uoephB1Z5MVkFJZo:-KW1uoephB1Z5MVkFJZp:b1t0nls) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/e01fd7bb11c38f948058c7ea18a5ac856fd15de1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectWizard.java#L83)):_

> ``` Java
>                 super.createControl(parent);
> 
>                 // doing this instead of performHelp() of the page explicitly
> ```

(comment formatting)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721)_

**Comment by ahie** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin8MavenProjectWizard.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KVzG_0C5Ky2GxXMTdGM:-KW2bDQIj-L3XjD9_-t2:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/60f877f0fa20a2303e8e5d7b21a7af8d798b88fc/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin8MavenProjectWizard.java#L30)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> only done below, not in the condition above
> </details>
> Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectWizard.java, line 58 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KW1u_H4llmKvzI-fAa4:-KW2as10epWtfcRJYLS9:bss4a2b) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/e01fd7bb11c38f948058c7ea18a5ac856fd15de1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectWizard.java#L58)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> no longer sets the title?
> </details>
> Removed.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectWizard.java, line 83 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721#-KW1uoephB1Z5MVkFJZo:-KW2bTSZT3Ks2eMPmYQ_:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/e01fd7bb11c38f948058c7ea18a5ac856fd15de1/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/VaadinMavenProjectWizard.java#L83)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> (comment formatting)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721)_

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/721)_

**Pull request merged**
