### PR TITLE
Change versions file name in MavenVersionManager

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/727)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727#-KWD-MMHvTz5FLd1Qo9j:-KWD-MMHvTz5FLd1Qo9k:b-ciom25) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/2803068c605257411abba778fa41d91802034d24/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L33)):_

> ``` Java
> 
>     private static final String ARCHETYPES_FILE_NAME = "eclipse-maven-archetypes.xml";
>     private static final String PRERELEASE_ARCHETYPES_FILE_NAME = "eclipse-maven-archetypes-prerelease.xml";
> ```

Unused.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727#-KWD-OSxUZWY4SWtjPEp:-KWD-OSxUZWY4SWtjPEq:b-ciom25) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/2803068c605257411abba778fa41d91802034d24/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L41)):_

> ``` Java
>             + ARCHETYPES_FILE_NAME;
> 
>     private static final String AVAILABLE_VAADIN_PRERELEASE_ARCHETYPES_URL = DownloadManager.VAADIN_DOWNLOAD_BASE_URL
> ```

Unused.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727)_

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/VersionUtil.java, line 97 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727#-KWDZow7vU6HQp09xauM:-KWDZow7vU6HQp09xauN:bh1c4qj) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/8b0386bf326f1a599fcf37ba494458390feba354/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/VersionUtil.java#L97)):_

> ``` Java
>             throws IOException {
>         String version = getManifestVersion(jarFile, "Implementation-Version");
>         if (version != null && version.matches("\\d+.\\d+.\\d+(\\..*)?")) {
> ```

add a comment to why this is here, and why we sometimes use bundle version instead (snapshots do not have the three-part version number)

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727#-KWD_59KWTzfKRw3Z4mi:-KWD_59KWTzfKRw3Z4mj:b-djetc3) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/2803068c605257411abba778fa41d91802034d24/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L35)):_

> ``` Java
>     private static final String PRERELEASE_ARCHETYPES_FILE_NAME = "eclipse-maven-archetypes-prerelease.xml";
> 
>     private static final String AVAILABLE_VAADIN_VERSIONS_7_URL = DownloadManager.VAADIN_DOWNLOAD_BASE_URL
> ```

rename without 7?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727)_

**Comment by ahie** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/VersionUtil.java, line 97 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727#-KWDZow7vU6HQp09xauM:-KWH0MlqZ4J4aIj5-mn8:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/8b0386bf326f1a599fcf37ba494458390feba354/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/VersionUtil.java#L97)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> add a comment to why this is here, and why we sometimes use bundle version instead (snapshots do not have the three-part version number)
> </details>
> Done.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727#-KWD_59KWTzfKRw3Z4mi:-KWH0MJgyAHvqXsh2pX8:b-896fix) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/2803068c605257411abba778fa41d91802034d24/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/network/MavenVersionManager.java#L35)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> rename without 7?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727)_

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/VersionUtil.java, line 97 at r2](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727#-KWDZow7vU6HQp09xauM:-KWH2dozBBGG0xUHlFaN:bgdrdwt) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/8b0386bf326f1a599fcf37ba494458390feba354/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/VersionUtil.java#L97)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Done.
> </details>
> to me, this still doesn't clarify why the implementation version would not always be in the expected form (snapshots)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727)_

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727)_

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/727#-:-KWH4UU0Ct56ajzeo1LI:bnfp4nl)_

**Pull request merged**
