### PR TITLE
Automatically use proxy settings from Eclipse when compiling widget set

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/695)

### CODE REVIEW

**Comment by elmot** [comment]
_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java, line 180 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695#-KI73v3EOub5enhrvEzO:-KI73v3FTyIFstNmV8g6:1773359480) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ed69b3263617bb2fe70e3c143c087054793057ed/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java#L180)):_

> ``` Java
>             }
> 
>             String httpProxyHost = System.getProperty("http.proxyHost");
> ```

Does not support:
http.nonProxyHosts
socksProxyHost 
socksProxyPort 
See http://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695)_

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java, line 78 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695#-KJ-op9Wt2W6iXHATO1D:-KJ-op9Wt2W6iXHATO1E:-1118856149) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/92f7e7efe7756ee40dff3d75d6cc7c294c9342e8/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java#L78)):_

> ``` Java
> 
>     private static final String[] PROXY_PROPERTIES = {"http.proxyHost","http.proxyPort", "http.nonProxyHosts",
>           "https.proxyHost","https.proxyPort", "socksProxyHost","socksProxyPort" };
> ```

whitespace as spaces rather than tabs here and next line (TBC)?

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java, line 182 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695#-KJ-oj6ehb-A9lEUp8Ll:-KJ-oj6ehb-A9lEUp8Lm:509820915) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/92f7e7efe7756ee40dff3d75d6cc7c294c9342e8/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java#L182)):_

> ``` Java
>             }
> 
>           for (String propertyName: PROXY_PROPERTIES)
> ```

whitespace as spaces rather than tabs (TBC)?

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java, line 186 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695#-KJ-obm0oaoqYbuYnJho:-KJ-obm0oaoqYbuYnJhp:497636076) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/92f7e7efe7756ee40dff3d75d6cc7c294c9342e8/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java#L186)):_

> ``` Java
>               String propertyValue = System.getProperty(propertyName);
>               if(propertyValue != null) {
>                    args.add("-D" + propertyName + "=" + propertyValue);
> ```

can this need quotes around the value? or are the values always safe without quotes?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695)_

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java, line 78 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695#-KJ-op9Wt2W6iXHATO1D:-KJ5ouEpv7Th4OMqZNUY:753787) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/92f7e7efe7756ee40dff3d75d6cc7c294c9342e8/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java#L78)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> whitespace as spaces rather than tabs here and next line (TBC)?
> </details>
> actually seems to be ok

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java, line 182 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695#-KJ-oj6ehb-A9lEUp8Ll:-KJ5oySzlw5N64KDq9xs:753787) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/92f7e7efe7756ee40dff3d75d6cc7c294c9342e8/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java#L182)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> whitespace as spaces rather than tabs (TBC)?
> </details>
> actually seems to be ok

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java, line 186 [r3]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695#-KJ-obm0oaoqYbuYnJho:-KJ5p-E_YTvgYm1JAShP:-1697981129) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/92f7e7efe7756ee40dff3d75d6cc7c294c9342e8/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java#L186)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> can this need quotes around the value? or are the values always safe without quotes?
> </details>
> apparently not needed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695)_

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java, line 180 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695#-KI73v3EOub5enhrvEzO:-KJ5pQDyf9G7UIFsmPoW:-973613370) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/ed69b3263617bb2fe70e3c143c087054793057ed/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/util/WidgetsetUtil.java#L180)):_
<details><summary>

<i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>



> Does not support:
> http.nonProxyHosts
> socksProxyHost 
> socksProxyPort 
> See http://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
> 
> </details>
> Fixed in latest commit

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/695)_

**Pull request merged**
