### PR TITLE
Maven theme widgetset

### PR DESCRIPTION
**Pull request by hesara**
Theme and widgetset are compiled using Maven in Maven projects.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/3)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/handlers/CompileThemeAndWidgetsetHandler.java, line 80 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/3#-KA_010-G6ej3qMS7H8x:-KA_010-G6ej3qMS7H8y:-595318132) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/7b1d86b8293098248ef3725f0c012afac13746ba/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/handlers/CompileThemeAndWidgetsetHandler.java#L80)):_
These empty implementations could be in the parent class.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/3)_

**Comment by tsuoanttila** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/3)_

**Comment by hesara** [comment]
_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/handlers/CompileThemeAndWidgetsetHandler.java, line 80 [r1]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/3#-KA_010-G6ej3qMS7H8x:-KA_1S3VntuslVrJPUvj:-499146009) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/7b1d86b8293098248ef3725f0c012afac13746ba/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/handlers/CompileThemeAndWidgetsetHandler.java#L80)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/3)_

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/3)_

**Pull request closed without merging**
