### PR TITLE
Integrate Amplitude analytics

### PR DESCRIPTION
**Pull request by szolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/770)

### CODE REVIEW

**Review by anssit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/770)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @szolo)

___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java, line 44 at r1](https://reviewable.io/reviews/vaadin/eclipse-plugin/770#-LiMnl9U8wxlI3dvmxS4:-LiMnl9U8wxlI3dvmxS5:b-iljntg) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/2d5a7ec8995cc60cf091d14bf9b8252c3e3db550/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java#L44)):*
> ```Java
>                 .getBooleanValue(JavaPreferenceKey.INSTALLED)) {
>             if (AnalyticsService.track(AnalyticsService.INSTALL_EVENT_TYPE)) {
>                 JavaPreferenceHandler
> ```

This should also be cleared on uninstall. Is that possible? Otherwise, there won't be install event on re-install. Or, on update. Do we need the install event at all?

**Review by szolo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/770)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @anssit)

___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java, line 44 at r1](https://reviewable.io/reviews/vaadin/eclipse-plugin/770#-LiMnl9U8wxlI3dvmxS4:-LiMpORU7LMqjb1M0rKP:b-ceyr6b) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/2d5a7ec8995cc60cf091d14bf9b8252c3e3db550/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java#L44)):*
<details><summary><i>Previously, anssit wrote…</i></summary><blockquote>

This should also be cleared on uninstall. Is that possible? Otherwise, there won't be install event on re-install. Or, on update. Do we need the install event at all?
</blockquote></details>

It's not possible to clean it after reinstall, at least to my knowledge. For the update it will be ignored.

**Review by anssit — COMMENTED** [review]
Code is fine, I'll test.

> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/770#-:-LiN01gIEzSkeNkT00hA:bn6ei34)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java, line 44 at r1](https://reviewable.io/reviews/vaadin/eclipse-plugin/770#-LiMnl9U8wxlI3dvmxS4:-LiN-jCs45FtoKUAzve4:b-k3zgmp) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/2d5a7ec8995cc60cf091d14bf9b8252c3e3db550/com.vaadin.integration.eclipse.flow/src/com/vaadin/integration/eclipse/flow/FlowPlugin.java#L44)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary><blockquote>

It's not possible to clean it after reinstall, at least to my knowledge. For the update it will be ignored.
</blockquote></details>

Ok, fair enough. Just we remember it'll capture 1 install for a user.

**Review by anssit — APPROVED** [review]
Tested, records my actions.

Tested also network disconnected cases when opening the wizard and downloading the project. The plug-in doesn't explode but gives reasonable error messages.
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/770#-:-LiN43I46b7h9DLBhJs2:b-ugrb99)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
