### PR TITLE
Redesign Maven archetype selection page (#644)

### PR DESCRIPTION
**Pull request by elmot**
Archetypes titles and descriptions are also changed

[Review on Reviewable](https://reviewable.io/reviews/vaadin/eclipse-plugin/645)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 96 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCyAkad0PMoQxCxgRz:-KBCyAkad0PMoQxCxgS-:1710236691) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L96)):_
unclear to me if calculating the height of one thing and setting it as minimum for another is correct or not, but seems to work ok

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 184 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCwdYMnG1j8V7VjgdX:-KBCwdYMnG1j8V7VjgdY:130388701) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L184)):_
perhaps this should only be done when leaving the archetype selection page

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645)_

**Comment by makoivis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 96 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCyAkad0PMoQxCxgRz:-KBD4-EZVoYcRs8iAQi0:711922763) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L96)):_
Aren't you really just getting the SWT_DEFAULT height?

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 184 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCwdYMnG1j8V7VjgdX:-KBD3ktriOXBmeLLNwFu:-1215195950) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L184)):_
does it matter what page you are on?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645)_

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java, line 96 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCyAkad0PMoQxCxgRz:-KBD4uXj93tkMTAKD0uS:-455073577) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectArchetypeSelectionView.java#L96)):_
SWT.DEFAULT is a constant (-1) that is just used as a hint for the size calculation, not returned as-is

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 184 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCwdYMnG1j8V7VjgdX:-KBD4_P0KrW9ezBdfNOg:-339261005) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L184)):_
My concern is that the current listener could reset some parameter values on the second page if doing Back and then Finish or something like that

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645)_

**Comment by makoivis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 184 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCwdYMnG1j8V7VjgdX:-KBD_vBChXOz6G1-QY73:2100901000) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L184)):_
How should that concern be addressed?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645)_

**Comment by elmot** [comment]
_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 184 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCwdYMnG1j8V7VjgdX:-KBE0On2Hu_jTuLzBZyI:2121136314) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L184)):_
For me does not sound like a problem

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645)_

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java, line 184 [r2]](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645#-KBCwdYMnG1j8V7VjgdX:-KBHH2I1hwsNhrTFZQwb:-736872368) ([raw file](https://github.com/vaadin/eclipse-plugin/blob/c066bca3c312f4eb9282a0737246e2e067a2e40b/com.vaadin.integration.eclipse/src/com/vaadin/integration/eclipse/wizards/Vaadin7MavenProjectWizard.java#L184)):_
tested that this is not a problem

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/eclipse-plugin/645)_

**Pull request closed without merging**
